# Project: 长整数处理软件
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = bigint.o main.o
LINKOBJ  = bigint.o main.o
LIBS     = -L"D:/c语言程序/Dev-Cpp/MinGW64/lib" -L"D:/c语言程序/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/c语言程序/Dev-Cpp/MinGW64/include" -I"D:/c语言程序/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/c语言程序/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/c语言程序/Dev-Cpp/MinGW64/include" -I"D:/c语言程序/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/c语言程序/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/c语言程序/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 长整数处理软件.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

bigint.o: bigint.c
	$(CC) -c bigint.c -o bigint.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
